-- Add summary columns to audit_projects table
ALTER TABLE public.audit_projects 
ADD COLUMN IF NOT EXISTS total_pages INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_links INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_images INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_meta_tags INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS technologies_found INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cms_detected BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS total_html_content INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS average_html_per_page INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pages_per_second DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_response_time INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS scraping_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS scraping_data JSONB;
